// <auto-generated />
using Castle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Castle.Migrations
{
    [DbContext(typeof(CastleDbContext))]
    partial class CastleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Castle.Models.PotentialPlayer", b =>
                {
                    b.Property<int>("PotentialPlayerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("Experience");

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.Property<string>("PreviousExperience");

                    b.HasKey("PotentialPlayerID");

                    b.ToTable("PotentialPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
